project 'MAIV-MobileApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'ARtFrame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MAIV-MobileApp
  pod 'ScalingCarousel'

end
